import type { CourseWithDetails, Profile } from '@/types/database'

export const MOCK_PROFILE: Profile = {
  id: 'demo-user-id',
  display_name: 'Manuel Amell',
  avatar_url: null,
  university: 'Universidad de Cartagena',
  faculty: 'Ingeniería de Sistemas',
  current_semester: '2026-2',
  passing_grade: 3.0,
  max_grade: 5.0,
  preferences: {
    theme: 'system',
    fontSize: 'normal',
    gridCompact: false,
    weekStartsOn: 'monday',
    timeFormat24h: true,
    defaultView: 'grid',
  },
  created_at: new Date().toISOString(),
  updated_at: new Date().toISOString(),
}

export const MOCK_COURSES: CourseWithDetails[] = [
  {
    id: 'mock-1',
    user_id: 'demo-user-id',
    code: 'CALCVEC',
    name: 'Cálculo Vectorial',
    professor: 'Gabriel Chanchi',
    email: 'gchanchi@unicartagena.edu.co',
    faculty: 'Ingeniería de Sistemas',
    semester: '2026-2',
    credits: 4,
    status: 'active',
    notes: 'Grupo B1 - Aula 304',
    color: 'blue',
    sort_order: 1,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    schedules: [
      {
        id: 's-1',
        course_id: 'mock-1',
        user_id: 'demo-user-id',
        day: 'Lunes',
        start_time: '08:40',
        end_time: '10:20',
        room: 'A-304',
        created_at: new Date().toISOString(),
      },
      {
        id: 's-2',
        course_id: 'mock-1',
        user_id: 'demo-user-id',
        day: 'Miércoles',
        start_time: '08:40',
        end_time: '10:20',
        room: 'A-304',
        created_at: new Date().toISOString(),
      },
    ],
    partials: [
      {
        id: 'p-1',
        course_id: 'mock-1',
        user_id: 'demo-user-id',
        name: 'Primer Parcial',
        grade: 4.2,
        percent: 30,
        sort_order: 0,
        created_at: new Date().toISOString(),
      },
      {
        id: 'p-2',
        course_id: 'mock-1',
        user_id: 'demo-user-id',
        name: 'Segundo Parcial',
        grade: 3.8,
        percent: 30,
        sort_order: 1,
        created_at: new Date().toISOString(),
      },
      {
        id: 'p-3',
        course_id: 'mock-1',
        user_id: 'demo-user-id',
        name: 'Examen Final',
        grade: null,
        percent: 40,
        sort_order: 2,
        created_at: new Date().toISOString(),
      },
    ],
  },
  {
    id: 'mock-2',
    user_id: 'demo-user-id',
    code: 'ESTDAT',
    name: 'Estructuras de Datos',
    professor: 'Carlos Mendoza',
    email: 'cmendoza@unicartagena.edu.co',
    faculty: 'Ingeniería de Sistemas',
    semester: '2026-2',
    credits: 3,
    status: 'active',
    notes: 'Laboratorio de Software',
    color: 'teal',
    sort_order: 2,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    schedules: [
      {
        id: 's-3',
        course_id: 'mock-2',
        user_id: 'demo-user-id',
        day: 'Martes',
        start_time: '10:20',
        end_time: '12:00',
        room: 'Lab-2',
        created_at: new Date().toISOString(),
      },
      {
        id: 's-4',
        course_id: 'mock-2',
        user_id: 'demo-user-id',
        day: 'Jueves',
        start_time: '10:20',
        end_time: '12:00',
        room: 'Lab-2',
        created_at: new Date().toISOString(),
      },
    ],
    partials: [
      {
        id: 'p-4',
        course_id: 'mock-2',
        user_id: 'demo-user-id',
        name: 'Taller de Grafos',
        grade: 4.8,
        percent: 30,
        sort_order: 0,
        created_at: new Date().toISOString(),
      },
      {
        id: 'p-5',
        course_id: 'mock-2',
        user_id: 'demo-user-id',
        name: 'Parcial Árboles',
        grade: 4.0,
        percent: 30,
        sort_order: 1,
        created_at: new Date().toISOString(),
      },
      {
        id: 'p-6',
        course_id: 'mock-2',
        user_id: 'demo-user-id',
        name: 'Proyecto Final',
        grade: null,
        percent: 40,
        sort_order: 2,
        created_at: new Date().toISOString(),
      },
    ],
  },
  {
    id: 'mock-3',
    user_id: 'demo-user-id',
    code: 'BASEDAT',
    name: 'Bases de Datos',
    professor: 'Ana Lucía Gómez',
    email: 'agomez@unicartagena.edu.co',
    faculty: 'Ingeniería de Sistemas',
    semester: '2026-2',
    credits: 3,
    status: 'active',
    notes: 'PostgreSQL y Modelado Relacional',
    color: 'orange',
    sort_order: 3,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    schedules: [
      {
        id: 's-5',
        course_id: 'mock-3',
        user_id: 'demo-user-id',
        day: 'Lunes',
        start_time: '14:00',
        end_time: '16:00',
        room: 'B-201',
        created_at: new Date().toISOString(),
      },
      {
        id: 's-6',
        course_id: 'mock-3',
        user_id: 'demo-user-id',
        day: 'Viernes',
        start_time: '08:00',
        end_time: '10:00',
        room: 'B-201',
        created_at: new Date().toISOString(),
      },
    ],
    partials: [
      {
        id: 'p-7',
        course_id: 'mock-3',
        user_id: 'demo-user-id',
        name: 'Normalización',
        grade: 4.5,
        percent: 30,
        sort_order: 0,
        created_at: new Date().toISOString(),
      },
      {
        id: 'p-8',
        course_id: 'mock-3',
        user_id: 'demo-user-id',
        name: 'SQL y Triggers',
        grade: null,
        percent: 35,
        sort_order: 1,
        created_at: new Date().toISOString(),
      },
      {
        id: 'p-9',
        course_id: 'mock-3',
        user_id: 'demo-user-id',
        name: 'Proyecto Integrador',
        grade: null,
        percent: 35,
        sort_order: 2,
        created_at: new Date().toISOString(),
      },
    ],
  },
]
