#!/bin/bash

APP_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
HOST_IP="${HOST:-localhost}"

echo ""
echo "╔══════════════════════════════════════════╗"
echo "║  📚 Amellify                              ║"
echo "╠══════════════════════════════════════════╣"
echo "║                                          ║"
echo "║  Modo Web (acceso desde cualquier         ║"
echo "║  dispositivo en la red):                  ║"
echo "║                                          ║"
echo "║  → http://$HOST_IP:3000             ║"
echo "║                                          ║"
echo "║  Para iniciar el servidor:                ║"
echo "║    ./iniciar-web.sh                      ║"
echo "║                                          ║"
echo "║  Electron requiere entorno gráfico.      ║"
echo "╚══════════════════════════════════════════╝"
echo ""